# Generated by Django 3.0.5 on 2020-08-26 07:56

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_details', djongo.models.fields.JSONField()),
                ('company_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='CandidateApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('curstats', models.CharField(max_length=50)),
                ('img', models.ImageField(default='img.jpg', max_length=50, upload_to='')),
            ],
            options={
                'db_table': 'candidate_apply',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='phone', max_length=20)),
                ('message', models.TextField(default='Message', max_length=500)),
            ],
            options={
                'db_table': 'contactpage',
            },
        ),
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='name', max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('compname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('jtitle', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jobpostdata',
            },
        ),
    ]
