# Generated by Django 3.0.7 on 2020-07-03 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'Email',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50)),
                ('phone', models.CharField(default='phone', max_length=20)),
                ('message', models.TextField(default='Message', max_length=500)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='main_app.CustomerEmail', unique_for_date=True)),
            ],
            options={
                'db_table': 'contactpage',
            },
        ),
        migrations.CreateModel(
            name='CandidateForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('datecreated', models.DateTimeField(default=datetime.datetime(2020, 7, 3, 12, 26, 8, 413685))),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='main_app.CustomerEmail', to_field='email')),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
    ]
