# Generated by Django 2.2.12 on 2020-07-27 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateform',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 15, 45, 41, 750312)),
        ),
    ]
