# Generated by Django 3.0.7 on 2020-07-03 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateform',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 12, 27, 49, 683311)),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main_app.CustomerEmail', unique_for_date=True),
        ),
    ]
