# Generated by Django 2.2.12 on 2020-08-24 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateform',
            name='category',
            field=models.CharField(choices=[('Accounting / Finance', 'Accounting / Finance'), ('Automotive Jobs', 'Automotive Jobs'), ('Design, Art', 'Design, Art'), ('Education Training', 'Education Training'), ('Health', 'Health'), ('Human Resource', 'Human Resource'), ('Restaurant', 'Restaurant'), ('Telecommunications', 'Telecommunications')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateform',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 11, 51, 31, 644586)),
        ),
    ]
