# Generated by Django 2.2.7 on 2020-09-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contactname', models.CharField(max_length=50)),
                ('contactemail', models.EmailField(max_length=254, unique=True)),
                ('contactphoneno', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
    ]
