# Generated by Django 2.2.12 on 2020-08-19 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200703_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateform',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 10, 55, 5, 75997)),
        ),
        migrations.AlterField(
            model_name='candidateform',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomerEmail',
        ),
    ]
