# Generated by Django 2.2.12 on 2020-08-24 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200824_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateform',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateform',
            name='datecreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 12, 10, 6, 863096)),
        ),
    ]
