# Generated by Django 2.2.13 on 2020-06-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contactpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='password',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='username',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='message',
            field=models.TextField(default='Message', max_length=500),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(default='email', max_length=254, unique=True),
        ),
    ]
