# Generated by Django 2.2.12 on 2020-08-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200824_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='datecreated',
        ),
    ]
