# Generated by Django 3.0.5 on 2020-08-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_candidate_datecreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('curstats', models.CharField(max_length=50)),
                ('img', models.ImageField(default='img.jpg', max_length=50, upload_to='')),
            ],
        ),
    ]
